version: 2.1

parameters:
  go-version:
    type: string
    default: "1.19"

executors:
  ubuntu_vm:
    machine:
      image: ubuntu-2004:202201-02

jobs:
  check_golang:
    docker:
      - image: "cimg/go:<< pipeline.parameters.go-version>>"
    steps:
      - checkout

      - run: |
          golang/scripts/build.sh

  run_kurtosis_package:
    executor: ubuntu_vm
    working_directory: /home/circleci/workspace
    steps:
      - checkout

      - attach_workspace:
          at: ./

      - run: |
          echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
          sudo apt update
          sudo apt install kurtosis-cli

      - run: |
          set -euo pipefail
          for i in 0 1 2 3 4 5 6 7 8 9 10; do
            echo "Running eth network package iteration #$i"
            kurtosis run github.com/kurtosis-tech/eth-network-package
          done

workflows:
  build:
    jobs:
      - check_golang:
          filters:
            branches:
              ignore:
                - main
      - run_kurtosis_package:
          requires:
            - check_golang
          filters:
            branches:
              ignore:
                - main
